// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    customer_id
) VALUES ($1) RETURNING id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_cents, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id, order_id, product_id, quantity, price_cents, status
`

type CreateOrderItemParams struct {
	OrderID    int64       `json:"order_id"`
	ProductID  int64       `json:"product_id"`
	Quantity   int32       `json:"quantity"`
	PriceCents int32       `json:"price_cents"`
	Status     pgtype.Text `json:"status"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceCents,
		arg.Status,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCents,
		&i.Status,
	)
	return i, err
}

const findProductByID = `-- name: FindProductByID :one
SELECT id, name, price_in_cents, quantity, created_at FROM products WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const findProductByIDForUpdate = `-- name: FindProductByIDForUpdate :one
SELECT id, name, price_in_cents, quantity, created_at FROM products WHERE id = $1 FOR UPDATE
`

func (q *Queries) FindProductByIDForUpdate(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByIDForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_cents, quantity, created_at FROM products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductQuantity = `-- name: UpdateProductQuantity :one
UPDATE products
SET quantity = $2
WHERE id = $1
RETURNING id, name, price_in_cents, quantity, created_at
`

type UpdateProductQuantityParams struct {
	ID       int64 `json:"id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductQuantity, arg.ID, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderItemStatus = `-- name: UpdateOrderItemStatus :one
UPDATE order_items
SET status = $2
WHERE id = $1
RETURNING id, order_id, product_id, quantity, price_cents, status
`

type UpdateOrderItemStatusParams struct {
	ID     int64       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateOrderItemStatus(ctx context.Context, arg UpdateOrderItemStatusParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItemStatus, arg.ID, arg.Status)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCents,
		&i.Status,
	)
	return i, err
}
